name: Research
dependencies:
- python = 3.9
- pandas
- numpy
- seaborn = 0.11.2
- matplotlib = 3.5.1
- scikit-learn = 1.1.1
- opencv
- pip:
  - keras-tuner
  - tensorflow
  - tensorflow_gnn
  - androguard